- name: Créer dossier pour keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Télécharger clé GPG Kubernetes
  get_url:
    url: "{{ k8s_repo_url }}Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
  become: yes

- name: Supprimer ancien dépôt Kubernetes si présent
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent
  become: yes

- name: Ajouter dépôt Kubernetes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] {{ k8s_repo_url }} /"
    state: present
    filename: kubernetes.list
    update_cache: yes
  become: yes

- name: Installer kubelet, kubeadm, kubectl
  apt:
    name:
      - "kubelet={{ k8s_deb_version }}"
      - "kubeadm={{ k8s_deb_version }}"
      - "kubectl={{ k8s_deb_version }}"
    state: present
  become: yes

- name: Hold kube packages
  ansible.builtin.command: "echo '{{ item }} hold' | sudo dpkg --set-selections"
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: yes
