---
# 1️⃣ Télécharger et convertir clé GPG Kubernetes (variabilisé)
- name: Télécharger et convertir clé GPG Kubernetes
  ansible.builtin.shell: |
    curl -fsSL {{ k8s_repo_url }}Release.key | gpg --dearmor -o {{ k8s_keyring_path }}
  args:
    creates: "{{ k8s_keyring_path }}"
  become: yes

# 2️⃣ Supprimer ancien dépôt Kubernetes si présent
- name: Supprimer ancien dépôt Kubernetes
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent
  become: yes

# 3️⃣ Ajouter dépôt Kubernetes variabilisé
- name: Ajouter dépôt Kubernetes
  ansible.builtin.shell: |
    echo "deb [signed-by={{ k8s_keyring_path }}] {{ k8s_repo_url }} /" | tee /etc/apt/sources.list.d/kubernetes.list
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list
  become: yes

# 4️⃣ Mettre à jour cache APT
- name: Mettre à jour cache APT
  ansible.builtin.apt:
    update_cache: yes
  become: yes

# 5️⃣ Installer kube packages avec version variabilisée
- name: Installer kube packages
  apt:
    name:
      - "kubelet={{ k8s_deb_version }}"
      - "kubeadm={{ k8s_deb_version }}"
      - "kubectl={{ k8s_deb_version }}"
    state: present
    update_cache: yes
  become: yes

# 6️⃣ Hold des packages
- name: Hold kube packages
  ansible.builtin.command: "echo '{{ item }} hold' | sudo dpkg --set-selections"
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: yes
