---
- name: Vérification installation existante
  include_tasks: prerequisites.yaml

- name: Installation containerd
  include_tasks: containerd.yaml

- name: Installation composants Kubernetes
  include_tasks: kube.yaml

- name: Configuration Master
  include_tasks: master.yaml
  when: kubernetes_role == "control_plane"

- name: Configuration Worker
  include_tasks: worker.yaml
  when: kubernetes_role == "worker"
