---
- name: Désactiver swap temporairement
  command: swapoff -a
  become: true

- name: Désactiver swap définitivement
  replace:
    path: /etc/fstab
    regexp: '(^.*swap.*$)'
    replace: '# \1'
  become: true

- name: Installer prérequis
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - conntrack
      - socat
    state: present
    update_cache: yes
  become: true

# 🔹 Charger les modules kernel immédiatement
- name: Charger les modules kernel overlay et br_netfilter
  shell: |
    modprobe overlay
    modprobe br_netfilter
  become: true

# 🔹 Configurer modules kernel persistants
- name: Modules kernel persistants
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    owner: root
    group: root
    mode: '0644'
  become: true

# 🔹 Configurer les paramètres sysctl
- name: Configurer sysctl pour Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables=1
      net.bridge.bridge-nf-call-ip6tables=1
      net.ipv4.ip_forward=1
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Appliquer sysctl
  command: sysctl --system
  become: true
